version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

      - run:
          name: Teste unitario
          command: |
            yarn test
